# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run: go get ./...
      - run: go test -v ./... --cover 
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run: mkdir -p build
      - run: go get ./...
      - run: go build -o build/service ./cmd/service/main.go
      - store_artifacts:
          path: build/service

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build