# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  go: circleci/go@2.2.3
jobs:
  test:
    executor:
      name: go/default
      tag: 1.23.4
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - go/mod-download
      - go/test:
          covermode: atomic
          failfast: true
workflows:
  test:
    jobs:
      - test